import 'dart:convert';
import 'package:drift/drift.dart';
import 'app_database.dart';
// Note: LoadsCompanion and StopsCompanion will be generated by build_runner in app_database.g.dart

class SeedData {
  static Future<void> seedDatabase(AppDatabase database) async {
    // Clear ALL existing data first
    await database.stopsDao.deleteAllStops();
    await database.loadsDao.deleteAllLoads();
    
    print('🗑️ Old data cleared');

    // Seed load - Realistic TIR route
    // ignore: undefined_class
    final load1 = LoadsCompanion.insert(
      id: 'load_001',
      loadNumber: 'TRK-2024-001',
      status: 'in_transit',
      assignedDriverId: const Value('driver_001'),
      assignedDriverName: const Value('Mehmet Demir (34 ABC 123)'),
      pickupAddress: 'İstanbul, Kadıköy, Anadolu Yakası Lojistik Merkezi',
      deliveryAddress: 'Antalya, Muratpaşa, OSB Merkez Dağıtım',
      pickupDate: DateTime.now().subtract(const Duration(hours: 6)),
      deliveryDate: DateTime.now().add(const Duration(hours: 12)),
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      rawData: jsonEncode({
        'id': 'load_001',
        'loadNumber': 'TRK-2024-001',
        'status': 'in_transit',
        'totalPackages': 45,
        'totalWeight': '12.5 ton',
        'cargoType': 'Elektronik Eşya',
        'vehiclePlate': '34 ABC 123',
      }),
    );

    await database.loadsDao.insertLoads([load1]);

    // TIR ROUTE: Istanbul → Bursa → Izmir → Antalya
    // All stops belong to same load for proper route visualization
    
    // Stop 1: Istanbul ✅ COMPLETED (Yükleme yapıldı, çıkış yapıldı)
    // ignore: undefined_class
    final stop1 = StopsCompanion.insert(
      id: 'stop_001',
      loadId: 'load_001',
      type: 'pickup',
      address: 'İstanbul, Kadıköy, Anadolu Yakası Lojistik Merkezi, E-5 Yan Yol No:47',
      latitude: 40.9848,
      longitude: 29.0262,
      geofenceRadius: 150.0,
      status: 'completed',
      expectedArrival: Value(DateTime.now().subtract(const Duration(hours: 6))),
      actualArrival: Value(DateTime.now().subtract(const Duration(hours: 6, minutes: 15))),
      actualDeparture: Value(DateTime.now().subtract(const Duration(hours: 5, minutes: 30))),
      notes: Value('45 paket yüklendi. Manifest onaylandı. Çıkış: 06:30'),
      rawData: jsonEncode({
        'id': 'stop_001',
        'packages': 45,
        'priority': 'high',
        'contactPerson': 'Ahmet Yılmaz',
        'contactPhone': '+90 532 123 4567',
      }),
    );

    // Stop 2: Bursa 🟠 IN PROGRESS (Şu anda yük indiriliyor)
    // ignore: undefined_class
    final stop2 = StopsCompanion.insert(
      id: 'stop_002',
      loadId: 'load_001',
      type: 'delivery',
      address: 'Bursa, Nilüfer, Organize Sanayi Bölgesi, 4. Cadde No:18',
      latitude: 40.1826,
      longitude: 29.0665,
      geofenceRadius: 150.0,
      status: 'in_progress',
      expectedArrival: Value(DateTime.now().subtract(const Duration(hours: 2))),
      actualArrival: Value(DateTime.now().subtract(const Duration(hours: 1, minutes: 50))),
      notes: Value('Teslim alınıyor. 15 paket indiriliyor. Tahmini süre: 30dk'),
      rawData: jsonEncode({
        'id': 'stop_002',
        'packages': 15,
        'priority': 'medium',
        'contactPerson': 'Mehmet Demir',
        'contactPhone': '+90 532 234 5678',
        'estimatedUnloadTime': 30,
      }),
    );

    // Stop 3: Izmir 🔴 PENDING (Bir sonraki durak)
    // ignore: undefined_class
    final stop3 = StopsCompanion.insert(
      id: 'stop_003',
      loadId: 'load_001',
      type: 'delivery',
      address: 'İzmir, Konak, Alsancak Liman Bölgesi, Atatürk Caddesi No:156',
      latitude: 38.4237,
      longitude: 27.1428,
      geofenceRadius: 150.0,
      status: 'pending',
      expectedArrival: Value(DateTime.now().add(const Duration(hours: 3))),
      notes: Value('Liman teslimatı. Gümrük belgesi gerekli. ETA: 3 saat'),
      rawData: jsonEncode({
        'id': 'stop_003',
        'packages': 20,
        'priority': 'high',
        'contactPerson': 'Ayşe Kaya',
        'contactPhone': '+90 532 345 6789',
        'requiresCustoms': true,
        'estimatedUnloadTime': 45,
      }),
    );

    // Stop 4: Antalya 🔴 PENDING (Son teslimat noktası)
    // ignore: undefined_class
    final stop4 = StopsCompanion.insert(
      id: 'stop_004',
      loadId: 'load_001',
      type: 'delivery',
      address: 'Antalya, Muratpaşa, OSB, Barınaklar Bulvarı No:89',
      latitude: 36.8969,
      longitude: 30.7133,
      geofenceRadius: 150.0,
      status: 'pending',
      expectedArrival: Value(DateTime.now().add(const Duration(hours: 8))),
      notes: Value('Son teslimat. 10 paket. Boş dönüş planlanacak. ETA: 8 saat'),
      rawData: jsonEncode({
        'id': 'stop_004',
        'packages': 10,
        'priority': 'normal',
        'contactPerson': 'Fatma Şahin',
        'contactPhone': '+90 532 456 7890',
        'estimatedUnloadTime': 25,
        'returnLoad': false,
      }),
    );

    await database.stopsDao.insertStops([stop1, stop2, stop3, stop4]);
    
    // Load 2: Ankara → İzmir (Assigned, not started yet)
    // ignore: undefined_class
    final load2 = LoadsCompanion.insert(
      id: 'load_002',
      loadNumber: 'TRK-2024-002',
      status: 'assigned',
      assignedDriverId: const Value('driver_002'),
      assignedDriverName: const Value('Ahmet Yılmaz (06 XYZ 456)'),
      pickupAddress: 'Ankara, Keçiören, Ana Depo',
      deliveryAddress: 'İzmir, Bornova, Liman Deposu',
      pickupDate: DateTime.now().add(const Duration(hours: 2)),
      deliveryDate: DateTime.now().add(const Duration(hours: 10)),
      createdAt: DateTime.now(),
      rawData: jsonEncode({
        'id': 'load_002',
        'loadNumber': 'TRK-2024-002',
        'status': 'assigned',
        'totalPackages': 30,
        'totalWeight': '8.2 ton',
        'cargoType': 'Tekstil Ürünleri',
        'vehiclePlate': '06 XYZ 456',
      }),
    );

    // Load 3: İzmir → Bursa (Completed)
    // ignore: undefined_class
    final load3 = LoadsCompanion.insert(
      id: 'load_003',
      loadNumber: 'TRK-2024-003',
      status: 'completed',
      assignedDriverId: const Value('driver_003'),
      assignedDriverName: const Value('Ali Kaya (35 DEF 789)'),
      pickupAddress: 'İzmir, Konak, Liman Bölgesi',
      deliveryAddress: 'Bursa, Osmangazi, Sanayi Sitesi',
      pickupDate: DateTime.now().subtract(const Duration(hours: 8)),
      deliveryDate: DateTime.now().subtract(const Duration(hours: 2)),
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      rawData: jsonEncode({
        'id': 'load_003',
        'loadNumber': 'TRK-2024-003',
        'status': 'completed',
        'totalPackages': 20,
        'totalWeight': '5.5 ton',
        'cargoType': 'Gıda Ürünleri',
        'vehiclePlate': '35 DEF 789',
      }),
    );

    await database.loadsDao.insertLoads([load2, load3]);
    
    print('✅ Database seeded: 3 loads, 4 stops');
    print('   Load 1: TRK-2024-001 (in_transit) - 4 stops');
    print('   Load 2: TRK-2024-002 (assigned)');
    print('   Load 3: TRK-2024-003 (completed)');
  }
}

